# config/packages/doctrine_migrations.yaml

doctrine_migrations:
    # List of namespace/path pairs to search for migrations, at least one required
    migrations_paths:
        'App\Migrations': '%kernel.project_dir%/src/App'

    # List of additional migration classes to be loaded, optional
    migrations:
        - 'App\Migrations\'